packages:
  - apps/*
  - packages/*

catalogMode: strict

catalog:
  "@fortawesome/fontawesome-svg-core": ^7.3.1
  "@fortawesome/free-solid-svg-icons": ^7.3.1
  "@fortawesome/react-fontawesome": ^3.5.0
  '@storybook/addon-a11y': ^10.5.10
  '@storybook/addon-vitest': ^10.5.10
  '@storybook/react-vite': ^10.5.10
  '@tailwindcss/vite': ^4.3.3
  '@tanstack/react-router': ^1.170.32
  "@testing-library/jest-dom": ^7.0.1
  "@testing-library/react": ^16.3.3
  "@testing-library/user-event": ^14.6.6
  "@types/node": ^26.4.0
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.5
  "@vitejs/plugin-react": ^6.1.1
  axios: ^1.20.0
  jsdom: ^30.0.1
  react: ^19.2.8
  react-dom: ^19.2.8
  react-markdown: ^10.1.0
  remark-gfm: ^4.0.1
  storybook: ^10.5.10
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  vite: ^8.2.2
  vitest: ^4.1.11

allowBuilds:
  esbuild: true
